/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 10-Mar-2018 15:39:28
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 3
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017b/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 7
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
   0.009566363304334,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
   0.009566363304334,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
   0.004730163924889,                 0,                 0 
  },
  {
                   1,                 0,                -1 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,    -1.99096899678,   0.9914139532086 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.999114354664,   0.9991190205759 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.990494213383,   0.9905396721502 
  },
  {
                   1,                 0,                 0 
  }
};
