/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
 * Generated on: 08-Apr-2018 15:24:55
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 4
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * /usr/local/MATLAB/R2017b/extern/include/tmwtypes.h 
 */
#define MWSPT_NSEC 9
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,2,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.7433525234027,                 0,                 0 
  },
  {
                   1,   0.0501446640335,                 1 
  },
  {
     0.5779052547403,                 0,                 0 
  },
  {
                   1,   0.4819366913207,                 1 
  },
  {
     0.4378788726627,                 0,                 0 
  },
  {
                   1,     1.36594535969,                 1 
  },
  {
     0.6143052152792,                 0,                 0 
  },
  {
                   1,                 1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,2,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -0.263103071538,    0.787083280888 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,-0.004193197220995,   0.4385174530679 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.3076159059695,   0.1662604535759 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   0.2286104305585,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
